[project]
name = "mapox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "einops>=0.8.1",
    "jax>=0.9.0",
    "pydantic>=2.12.5",
    "pygame-ce>=2.5.6",
    "python-ffmpeg>=2.0.12",
]
